import type { JobOffer } from "../types/job";

export const parseRSS = async (): Promise<JobOffer[]> => {
  try {
    // Fetch pre-processed JSON data (generated by GitHub Actions)
    // Add timestamp to prevent browser caching of the static file
    const response = await fetch(`/jobs.json?t=${Date.now()}`);
    if (!response.ok) throw new Error("Failed to load jobs data");
    
    const jobs = await response.json();
    return jobs;
  } catch (error) {
    console.error("Error loading jobs:", error);
    return [];
  }
};
// Removed XML Parser dependency and logic from frontend since it's now handled by the script
// But we keep the file clean. Wait, if I remove logic, I verified the script replicates it.
// The frontend purely consumes the JSON now.


